apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1 # Number of replicas (adjust as needed)
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: techsckoolacr.azurecr.io/myflaskapp:v4
        # ports:
        # - containerPort: 5000 # Port on which your Flask app is running
      imagePullSecrets: # Add this section
      - name: imagepullsec


---

apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80 # Port to expose on the service
      targetPort: 80 # Port your Flask app is running on

